version: '3.8'

services:
  # PostgreSQL-Datenbank
  postgres:
    image: postgres:latest
    container_name: weatherdb
    restart: always
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./weatherdb_dump.sql:/docker-entrypoint-initdb.d/weatherdb_dump.sql

  # Spring Boot Backend
  backend:
    build: ./backend  # <- Stelle sicher, dass es das Backend-Verzeichnis verwendet
    container_name: weather-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/weatherdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
