# Verwende ein schlankes Java-Image
FROM openjdk:23-jdk-slim
# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die erstellte JAR-Datei
COPY target/weather-widget-0.0.1-SNAPSHOT.jar app.jar

# Spring Boot Anwendung starten
CMD ["java", "-jar", "app.jar"]
